# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: No Token Needed - Metrics
on:
  # Schedule daily updates# each [] is the option we can set according to the info below.
  # [min (0-59)] [hour (0-23)] [day of month (1-31)] [month (1-12)] [day of week (0-6)]
  # 0 11 means its running at 6AM EST 
  schedule: [{cron: "10 1 * * *"}]
  # Lines below let you run workflow manually and on each commit
  #workflow_dispatch:
  #push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - uses: lowlighter/metrics@latest
        name: Featured star list languages
        with:
          filename: metrics/plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          
      - uses: lowlighter/metrics@lates
        name: Icons
        with:
            filename: metrics/plugin.topics.icons.svg
            token: NOT_NEEDED
            base: ""
            plugin_topics: yes
            plugin_topics_limit: 15
            plugin_topics_mode: icons
            
      - uses: lowlighter/metrics@latest
        name: Comic of the Day
        with:
          filename: metrics/plugin.screenshot.comic.svg
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: Comic of the Day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
          
      - name: Fortune
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/plugin.fortune.svg
          token: NOT_NEEDED
          base: ""
          plugin_fortune: yes
          
