# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: One at a time - Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "10 5 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Yohn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          # Furtune Cookie
          plugin_fortune: yes
          # half calendar thing
          plugin_isocalendar: yes

